name: Generate Podcast Feeds

on: 
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run feed generator
        uses: KhalidRouissi1/podcast-generator@main
